/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardKycRouteImport } from './routes/_authenticated/dashboard.kyc'
import { Route as AuthenticatedDashboardMatrixRouteImport } from './routes/_authenticated/dashboard.matrix'
import { Route as AuthenticatedDashboardMembershipRouteImport } from './routes/_authenticated/dashboard.membership'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardPerformanceRouteImport } from './routes/_authenticated/dashboard.performance'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard.wallet'
import { Route as ApiPublicHooksLicenseGraceRouteImport } from './routes/api/public/hooks/license-grace'
import { Route as ApiPublicHooksMatrixCommissionsRouteImport } from './routes/api/public/hooks/matrix-commissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKycRoute =
  AuthenticatedDashboardKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatrixRoute =
  AuthenticatedDashboardMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMembershipRoute =
  AuthenticatedDashboardMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerformanceRoute =
  AuthenticatedDashboardPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicHooksLicenseGraceRoute =
  ApiPublicHooksLicenseGraceRouteImport.update({
    id: '/api/public/hooks/license-grace',
    path: '/api/public/hooks/license-grace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatrixCommissionsRoute =
  ApiPublicHooksMatrixCommissionsRouteImport.update({
    id: '/api/public/hooks/matrix-commissions',
    path: '/api/public/hooks/matrix-commissions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/_authenticated/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/_authenticated/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/dashboard'
    | '/shop/$slug'
    | '/shop/'
    | '/dashboard/kyc'
    | '/dashboard/matrix'
    | '/dashboard/membership'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/wallet'
    | '/dashboard/'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/shop/$slug'
    | '/shop'
    | '/dashboard/kyc'
    | '/dashboard/matrix'
    | '/dashboard/membership'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/wallet'
    | '/dashboard'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/_authenticated/dashboard'
    | '/shop/$slug'
    | '/shop/'
    | '/_authenticated/dashboard/kyc'
    | '/_authenticated/dashboard/matrix'
    | '/_authenticated/dashboard/membership'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/performance'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/dashboard/'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  RegisterRoute: typeof RegisterRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicHooksLicenseGraceRoute: typeof ApiPublicHooksLicenseGraceRoute
  ApiPublicHooksMatrixCommissionsRoute: typeof ApiPublicHooksMatrixCommissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/kyc': {
      id: '/_authenticated/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof AuthenticatedDashboardKycRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matrix': {
      id: '/_authenticated/dashboard/matrix'
      path: '/matrix'
      fullPath: '/dashboard/matrix'
      preLoaderRoute: typeof AuthenticatedDashboardMatrixRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/membership': {
      id: '/_authenticated/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof AuthenticatedDashboardMembershipRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/performance': {
      id: '/_authenticated/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof AuthenticatedDashboardPerformanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/hooks/license-grace': {
      id: '/api/public/hooks/license-grace'
      path: '/api/public/hooks/license-grace'
      fullPath: '/api/public/hooks/license-grace'
      preLoaderRoute: typeof ApiPublicHooksLicenseGraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/matrix-commissions': {
      id: '/api/public/hooks/matrix-commissions'
      path: '/api/public/hooks/matrix-commissions'
      fullPath: '/api/public/hooks/matrix-commissions'
      preLoaderRoute: typeof ApiPublicHooksMatrixCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardKycRoute: typeof AuthenticatedDashboardKycRoute
  AuthenticatedDashboardMatrixRoute: typeof AuthenticatedDashboardMatrixRoute
  AuthenticatedDashboardMembershipRoute: typeof AuthenticatedDashboardMembershipRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPerformanceRoute: typeof AuthenticatedDashboardPerformanceRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardKycRoute: AuthenticatedDashboardKycRoute,
    AuthenticatedDashboardMatrixRoute: AuthenticatedDashboardMatrixRoute,
    AuthenticatedDashboardMembershipRoute:
      AuthenticatedDashboardMembershipRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPerformanceRoute:
      AuthenticatedDashboardPerformanceRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  RegisterRoute: RegisterRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicHooksLicenseGraceRoute: ApiPublicHooksLicenseGraceRoute,
  ApiPublicHooksMatrixCommissionsRoute: ApiPublicHooksMatrixCommissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
