/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedConsoleX7q9f4k2m8RouteImport } from './routes/_authenticated/console-x7q9f4k2m8'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedConsoleX7q9f4k2m8IndexRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.index'
import { Route as AuthenticatedConsoleX7q9f4k2m8BrandingRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.branding'
import { Route as AuthenticatedConsoleX7q9f4k2m8CommissionsRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.commissions'
import { Route as AuthenticatedConsoleX7q9f4k2m8ContentRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.content'
import { Route as AuthenticatedConsoleX7q9f4k2m8InventoryRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.inventory'
import { Route as AuthenticatedConsoleX7q9f4k2m8KycRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.kyc'
import { Route as AuthenticatedConsoleX7q9f4k2m8MembersRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.members'
import { Route as AuthenticatedConsoleX7q9f4k2m8OrdersRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.orders'
import { Route as AuthenticatedConsoleX7q9f4k2m8ProductsRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.products'
import { Route as AuthenticatedConsoleX7q9f4k2m8RanksRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.ranks'
import { Route as AuthenticatedConsoleX7q9f4k2m8StaffRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.staff'
import { Route as AuthenticatedConsoleX7q9f4k2m8WithdrawalsRouteImport } from './routes/_authenticated/console-x7q9f4k2m8.withdrawals'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardKycRouteImport } from './routes/_authenticated/dashboard.kyc'
import { Route as AuthenticatedDashboardMatrixRouteImport } from './routes/_authenticated/dashboard.matrix'
import { Route as AuthenticatedDashboardMembershipRouteImport } from './routes/_authenticated/dashboard.membership'
import { Route as AuthenticatedDashboardNewsRouteImport } from './routes/_authenticated/dashboard.news'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardPerformanceRouteImport } from './routes/_authenticated/dashboard.performance'
import { Route as AuthenticatedDashboardWalletRouteImport } from './routes/_authenticated/dashboard.wallet'
import { Route as ApiPublicHooksLicenseGraceRouteImport } from './routes/api/public/hooks/license-grace'
import { Route as ApiPublicHooksMatrixCommissionsRouteImport } from './routes/api/public/hooks/matrix-commissions'
import { Route as ApiPublicHooksMonthlyCycleRouteImport } from './routes/api/public/hooks/monthly-cycle'
import { Route as ApiPublicHooksWeeklyCycleRouteImport } from './routes/api/public/hooks/weekly-cycle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleX7q9f4k2m8Route =
  AuthenticatedConsoleX7q9f4k2m8RouteImport.update({
    id: '/console-x7q9f4k2m8',
    path: '/console-x7q9f4k2m8',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsoleX7q9f4k2m8IndexRoute =
  AuthenticatedConsoleX7q9f4k2m8IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8BrandingRoute =
  AuthenticatedConsoleX7q9f4k2m8BrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8CommissionsRoute =
  AuthenticatedConsoleX7q9f4k2m8CommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8ContentRoute =
  AuthenticatedConsoleX7q9f4k2m8ContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8InventoryRoute =
  AuthenticatedConsoleX7q9f4k2m8InventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8KycRoute =
  AuthenticatedConsoleX7q9f4k2m8KycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8MembersRoute =
  AuthenticatedConsoleX7q9f4k2m8MembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8OrdersRoute =
  AuthenticatedConsoleX7q9f4k2m8OrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8ProductsRoute =
  AuthenticatedConsoleX7q9f4k2m8ProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8RanksRoute =
  AuthenticatedConsoleX7q9f4k2m8RanksRouteImport.update({
    id: '/ranks',
    path: '/ranks',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8StaffRoute =
  AuthenticatedConsoleX7q9f4k2m8StaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute =
  AuthenticatedConsoleX7q9f4k2m8WithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedConsoleX7q9f4k2m8Route,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKycRoute =
  AuthenticatedDashboardKycRouteImport.update({
    id: '/kyc',
    path: '/kyc',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMatrixRoute =
  AuthenticatedDashboardMatrixRouteImport.update({
    id: '/matrix',
    path: '/matrix',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMembershipRoute =
  AuthenticatedDashboardMembershipRouteImport.update({
    id: '/membership',
    path: '/membership',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNewsRoute =
  AuthenticatedDashboardNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPerformanceRoute =
  AuthenticatedDashboardPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWalletRoute =
  AuthenticatedDashboardWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicHooksLicenseGraceRoute =
  ApiPublicHooksLicenseGraceRouteImport.update({
    id: '/api/public/hooks/license-grace',
    path: '/api/public/hooks/license-grace',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMatrixCommissionsRoute =
  ApiPublicHooksMatrixCommissionsRouteImport.update({
    id: '/api/public/hooks/matrix-commissions',
    path: '/api/public/hooks/matrix-commissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyCycleRoute =
  ApiPublicHooksMonthlyCycleRouteImport.update({
    id: '/api/public/hooks/monthly-cycle',
    path: '/api/public/hooks/monthly-cycle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyCycleRoute =
  ApiPublicHooksWeeklyCycleRouteImport.update({
    id: '/api/public/hooks/weekly-cycle',
    path: '/api/public/hooks/weekly-cycle',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/console-x7q9f4k2m8': typeof AuthenticatedConsoleX7q9f4k2m8RouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/console-x7q9f4k2m8/branding': typeof AuthenticatedConsoleX7q9f4k2m8BrandingRoute
  '/console-x7q9f4k2m8/commissions': typeof AuthenticatedConsoleX7q9f4k2m8CommissionsRoute
  '/console-x7q9f4k2m8/content': typeof AuthenticatedConsoleX7q9f4k2m8ContentRoute
  '/console-x7q9f4k2m8/inventory': typeof AuthenticatedConsoleX7q9f4k2m8InventoryRoute
  '/console-x7q9f4k2m8/kyc': typeof AuthenticatedConsoleX7q9f4k2m8KycRoute
  '/console-x7q9f4k2m8/members': typeof AuthenticatedConsoleX7q9f4k2m8MembersRoute
  '/console-x7q9f4k2m8/orders': typeof AuthenticatedConsoleX7q9f4k2m8OrdersRoute
  '/console-x7q9f4k2m8/products': typeof AuthenticatedConsoleX7q9f4k2m8ProductsRoute
  '/console-x7q9f4k2m8/ranks': typeof AuthenticatedConsoleX7q9f4k2m8RanksRoute
  '/console-x7q9f4k2m8/staff': typeof AuthenticatedConsoleX7q9f4k2m8StaffRoute
  '/console-x7q9f4k2m8/withdrawals': typeof AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute
  '/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/dashboard/news': typeof AuthenticatedDashboardNewsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/console-x7q9f4k2m8/': typeof AuthenticatedConsoleX7q9f4k2m8IndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
  '/api/public/hooks/monthly-cycle': typeof ApiPublicHooksMonthlyCycleRoute
  '/api/public/hooks/weekly-cycle': typeof ApiPublicHooksWeeklyCycleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/console-x7q9f4k2m8/branding': typeof AuthenticatedConsoleX7q9f4k2m8BrandingRoute
  '/console-x7q9f4k2m8/commissions': typeof AuthenticatedConsoleX7q9f4k2m8CommissionsRoute
  '/console-x7q9f4k2m8/content': typeof AuthenticatedConsoleX7q9f4k2m8ContentRoute
  '/console-x7q9f4k2m8/inventory': typeof AuthenticatedConsoleX7q9f4k2m8InventoryRoute
  '/console-x7q9f4k2m8/kyc': typeof AuthenticatedConsoleX7q9f4k2m8KycRoute
  '/console-x7q9f4k2m8/members': typeof AuthenticatedConsoleX7q9f4k2m8MembersRoute
  '/console-x7q9f4k2m8/orders': typeof AuthenticatedConsoleX7q9f4k2m8OrdersRoute
  '/console-x7q9f4k2m8/products': typeof AuthenticatedConsoleX7q9f4k2m8ProductsRoute
  '/console-x7q9f4k2m8/ranks': typeof AuthenticatedConsoleX7q9f4k2m8RanksRoute
  '/console-x7q9f4k2m8/staff': typeof AuthenticatedConsoleX7q9f4k2m8StaffRoute
  '/console-x7q9f4k2m8/withdrawals': typeof AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute
  '/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/dashboard/news': typeof AuthenticatedDashboardNewsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/console-x7q9f4k2m8': typeof AuthenticatedConsoleX7q9f4k2m8IndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
  '/api/public/hooks/monthly-cycle': typeof ApiPublicHooksMonthlyCycleRoute
  '/api/public/hooks/weekly-cycle': typeof ApiPublicHooksWeeklyCycleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/register': typeof RegisterRoute
  '/_authenticated/console-x7q9f4k2m8': typeof AuthenticatedConsoleX7q9f4k2m8RouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/console-x7q9f4k2m8/branding': typeof AuthenticatedConsoleX7q9f4k2m8BrandingRoute
  '/_authenticated/console-x7q9f4k2m8/commissions': typeof AuthenticatedConsoleX7q9f4k2m8CommissionsRoute
  '/_authenticated/console-x7q9f4k2m8/content': typeof AuthenticatedConsoleX7q9f4k2m8ContentRoute
  '/_authenticated/console-x7q9f4k2m8/inventory': typeof AuthenticatedConsoleX7q9f4k2m8InventoryRoute
  '/_authenticated/console-x7q9f4k2m8/kyc': typeof AuthenticatedConsoleX7q9f4k2m8KycRoute
  '/_authenticated/console-x7q9f4k2m8/members': typeof AuthenticatedConsoleX7q9f4k2m8MembersRoute
  '/_authenticated/console-x7q9f4k2m8/orders': typeof AuthenticatedConsoleX7q9f4k2m8OrdersRoute
  '/_authenticated/console-x7q9f4k2m8/products': typeof AuthenticatedConsoleX7q9f4k2m8ProductsRoute
  '/_authenticated/console-x7q9f4k2m8/ranks': typeof AuthenticatedConsoleX7q9f4k2m8RanksRoute
  '/_authenticated/console-x7q9f4k2m8/staff': typeof AuthenticatedConsoleX7q9f4k2m8StaffRoute
  '/_authenticated/console-x7q9f4k2m8/withdrawals': typeof AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute
  '/_authenticated/dashboard/kyc': typeof AuthenticatedDashboardKycRoute
  '/_authenticated/dashboard/matrix': typeof AuthenticatedDashboardMatrixRoute
  '/_authenticated/dashboard/membership': typeof AuthenticatedDashboardMembershipRoute
  '/_authenticated/dashboard/news': typeof AuthenticatedDashboardNewsRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/_authenticated/dashboard/wallet': typeof AuthenticatedDashboardWalletRoute
  '/_authenticated/console-x7q9f4k2m8/': typeof AuthenticatedConsoleX7q9f4k2m8IndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hooks/license-grace': typeof ApiPublicHooksLicenseGraceRoute
  '/api/public/hooks/matrix-commissions': typeof ApiPublicHooksMatrixCommissionsRoute
  '/api/public/hooks/monthly-cycle': typeof ApiPublicHooksMonthlyCycleRoute
  '/api/public/hooks/weekly-cycle': typeof ApiPublicHooksWeeklyCycleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/console-x7q9f4k2m8'
    | '/dashboard'
    | '/shop/$slug'
    | '/shop/'
    | '/console-x7q9f4k2m8/branding'
    | '/console-x7q9f4k2m8/commissions'
    | '/console-x7q9f4k2m8/content'
    | '/console-x7q9f4k2m8/inventory'
    | '/console-x7q9f4k2m8/kyc'
    | '/console-x7q9f4k2m8/members'
    | '/console-x7q9f4k2m8/orders'
    | '/console-x7q9f4k2m8/products'
    | '/console-x7q9f4k2m8/ranks'
    | '/console-x7q9f4k2m8/staff'
    | '/console-x7q9f4k2m8/withdrawals'
    | '/dashboard/kyc'
    | '/dashboard/matrix'
    | '/dashboard/membership'
    | '/dashboard/news'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/wallet'
    | '/console-x7q9f4k2m8/'
    | '/dashboard/'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
    | '/api/public/hooks/monthly-cycle'
    | '/api/public/hooks/weekly-cycle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/shop/$slug'
    | '/shop'
    | '/console-x7q9f4k2m8/branding'
    | '/console-x7q9f4k2m8/commissions'
    | '/console-x7q9f4k2m8/content'
    | '/console-x7q9f4k2m8/inventory'
    | '/console-x7q9f4k2m8/kyc'
    | '/console-x7q9f4k2m8/members'
    | '/console-x7q9f4k2m8/orders'
    | '/console-x7q9f4k2m8/products'
    | '/console-x7q9f4k2m8/ranks'
    | '/console-x7q9f4k2m8/staff'
    | '/console-x7q9f4k2m8/withdrawals'
    | '/dashboard/kyc'
    | '/dashboard/matrix'
    | '/dashboard/membership'
    | '/dashboard/news'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/wallet'
    | '/console-x7q9f4k2m8'
    | '/dashboard'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
    | '/api/public/hooks/monthly-cycle'
    | '/api/public/hooks/weekly-cycle'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/membership'
    | '/register'
    | '/_authenticated/console-x7q9f4k2m8'
    | '/_authenticated/dashboard'
    | '/shop/$slug'
    | '/shop/'
    | '/_authenticated/console-x7q9f4k2m8/branding'
    | '/_authenticated/console-x7q9f4k2m8/commissions'
    | '/_authenticated/console-x7q9f4k2m8/content'
    | '/_authenticated/console-x7q9f4k2m8/inventory'
    | '/_authenticated/console-x7q9f4k2m8/kyc'
    | '/_authenticated/console-x7q9f4k2m8/members'
    | '/_authenticated/console-x7q9f4k2m8/orders'
    | '/_authenticated/console-x7q9f4k2m8/products'
    | '/_authenticated/console-x7q9f4k2m8/ranks'
    | '/_authenticated/console-x7q9f4k2m8/staff'
    | '/_authenticated/console-x7q9f4k2m8/withdrawals'
    | '/_authenticated/dashboard/kyc'
    | '/_authenticated/dashboard/matrix'
    | '/_authenticated/dashboard/membership'
    | '/_authenticated/dashboard/news'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/performance'
    | '/_authenticated/dashboard/wallet'
    | '/_authenticated/console-x7q9f4k2m8/'
    | '/_authenticated/dashboard/'
    | '/api/public/hooks/license-grace'
    | '/api/public/hooks/matrix-commissions'
    | '/api/public/hooks/monthly-cycle'
    | '/api/public/hooks/weekly-cycle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  RegisterRoute: typeof RegisterRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicHooksLicenseGraceRoute: typeof ApiPublicHooksLicenseGraceRoute
  ApiPublicHooksMatrixCommissionsRoute: typeof ApiPublicHooksMatrixCommissionsRoute
  ApiPublicHooksMonthlyCycleRoute: typeof ApiPublicHooksMonthlyCycleRoute
  ApiPublicHooksWeeklyCycleRoute: typeof ApiPublicHooksWeeklyCycleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console-x7q9f4k2m8': {
      id: '/_authenticated/console-x7q9f4k2m8'
      path: '/console-x7q9f4k2m8'
      fullPath: '/console-x7q9f4k2m8'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/console-x7q9f4k2m8/': {
      id: '/_authenticated/console-x7q9f4k2m8/'
      path: '/'
      fullPath: '/console-x7q9f4k2m8/'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8IndexRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/branding': {
      id: '/_authenticated/console-x7q9f4k2m8/branding'
      path: '/branding'
      fullPath: '/console-x7q9f4k2m8/branding'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8BrandingRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/commissions': {
      id: '/_authenticated/console-x7q9f4k2m8/commissions'
      path: '/commissions'
      fullPath: '/console-x7q9f4k2m8/commissions'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8CommissionsRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/content': {
      id: '/_authenticated/console-x7q9f4k2m8/content'
      path: '/content'
      fullPath: '/console-x7q9f4k2m8/content'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8ContentRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/inventory': {
      id: '/_authenticated/console-x7q9f4k2m8/inventory'
      path: '/inventory'
      fullPath: '/console-x7q9f4k2m8/inventory'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8InventoryRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/kyc': {
      id: '/_authenticated/console-x7q9f4k2m8/kyc'
      path: '/kyc'
      fullPath: '/console-x7q9f4k2m8/kyc'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8KycRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/members': {
      id: '/_authenticated/console-x7q9f4k2m8/members'
      path: '/members'
      fullPath: '/console-x7q9f4k2m8/members'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8MembersRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/orders': {
      id: '/_authenticated/console-x7q9f4k2m8/orders'
      path: '/orders'
      fullPath: '/console-x7q9f4k2m8/orders'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8OrdersRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/products': {
      id: '/_authenticated/console-x7q9f4k2m8/products'
      path: '/products'
      fullPath: '/console-x7q9f4k2m8/products'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8ProductsRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/ranks': {
      id: '/_authenticated/console-x7q9f4k2m8/ranks'
      path: '/ranks'
      fullPath: '/console-x7q9f4k2m8/ranks'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8RanksRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/staff': {
      id: '/_authenticated/console-x7q9f4k2m8/staff'
      path: '/staff'
      fullPath: '/console-x7q9f4k2m8/staff'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8StaffRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/console-x7q9f4k2m8/withdrawals': {
      id: '/_authenticated/console-x7q9f4k2m8/withdrawals'
      path: '/withdrawals'
      fullPath: '/console-x7q9f4k2m8/withdrawals'
      preLoaderRoute: typeof AuthenticatedConsoleX7q9f4k2m8WithdrawalsRouteImport
      parentRoute: typeof AuthenticatedConsoleX7q9f4k2m8Route
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/kyc': {
      id: '/_authenticated/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof AuthenticatedDashboardKycRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/matrix': {
      id: '/_authenticated/dashboard/matrix'
      path: '/matrix'
      fullPath: '/dashboard/matrix'
      preLoaderRoute: typeof AuthenticatedDashboardMatrixRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/membership': {
      id: '/_authenticated/dashboard/membership'
      path: '/membership'
      fullPath: '/dashboard/membership'
      preLoaderRoute: typeof AuthenticatedDashboardMembershipRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/news': {
      id: '/_authenticated/dashboard/news'
      path: '/news'
      fullPath: '/dashboard/news'
      preLoaderRoute: typeof AuthenticatedDashboardNewsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/performance': {
      id: '/_authenticated/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof AuthenticatedDashboardPerformanceRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/wallet': {
      id: '/_authenticated/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AuthenticatedDashboardWalletRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/hooks/license-grace': {
      id: '/api/public/hooks/license-grace'
      path: '/api/public/hooks/license-grace'
      fullPath: '/api/public/hooks/license-grace'
      preLoaderRoute: typeof ApiPublicHooksLicenseGraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/matrix-commissions': {
      id: '/api/public/hooks/matrix-commissions'
      path: '/api/public/hooks/matrix-commissions'
      fullPath: '/api/public/hooks/matrix-commissions'
      preLoaderRoute: typeof ApiPublicHooksMatrixCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-cycle': {
      id: '/api/public/hooks/monthly-cycle'
      path: '/api/public/hooks/monthly-cycle'
      fullPath: '/api/public/hooks/monthly-cycle'
      preLoaderRoute: typeof ApiPublicHooksMonthlyCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-cycle': {
      id: '/api/public/hooks/weekly-cycle'
      path: '/api/public/hooks/weekly-cycle'
      fullPath: '/api/public/hooks/weekly-cycle'
      preLoaderRoute: typeof ApiPublicHooksWeeklyCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConsoleX7q9f4k2m8RouteChildren {
  AuthenticatedConsoleX7q9f4k2m8BrandingRoute: typeof AuthenticatedConsoleX7q9f4k2m8BrandingRoute
  AuthenticatedConsoleX7q9f4k2m8CommissionsRoute: typeof AuthenticatedConsoleX7q9f4k2m8CommissionsRoute
  AuthenticatedConsoleX7q9f4k2m8ContentRoute: typeof AuthenticatedConsoleX7q9f4k2m8ContentRoute
  AuthenticatedConsoleX7q9f4k2m8InventoryRoute: typeof AuthenticatedConsoleX7q9f4k2m8InventoryRoute
  AuthenticatedConsoleX7q9f4k2m8KycRoute: typeof AuthenticatedConsoleX7q9f4k2m8KycRoute
  AuthenticatedConsoleX7q9f4k2m8MembersRoute: typeof AuthenticatedConsoleX7q9f4k2m8MembersRoute
  AuthenticatedConsoleX7q9f4k2m8OrdersRoute: typeof AuthenticatedConsoleX7q9f4k2m8OrdersRoute
  AuthenticatedConsoleX7q9f4k2m8ProductsRoute: typeof AuthenticatedConsoleX7q9f4k2m8ProductsRoute
  AuthenticatedConsoleX7q9f4k2m8RanksRoute: typeof AuthenticatedConsoleX7q9f4k2m8RanksRoute
  AuthenticatedConsoleX7q9f4k2m8StaffRoute: typeof AuthenticatedConsoleX7q9f4k2m8StaffRoute
  AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute: typeof AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute
  AuthenticatedConsoleX7q9f4k2m8IndexRoute: typeof AuthenticatedConsoleX7q9f4k2m8IndexRoute
}

const AuthenticatedConsoleX7q9f4k2m8RouteChildren: AuthenticatedConsoleX7q9f4k2m8RouteChildren =
  {
    AuthenticatedConsoleX7q9f4k2m8BrandingRoute:
      AuthenticatedConsoleX7q9f4k2m8BrandingRoute,
    AuthenticatedConsoleX7q9f4k2m8CommissionsRoute:
      AuthenticatedConsoleX7q9f4k2m8CommissionsRoute,
    AuthenticatedConsoleX7q9f4k2m8ContentRoute:
      AuthenticatedConsoleX7q9f4k2m8ContentRoute,
    AuthenticatedConsoleX7q9f4k2m8InventoryRoute:
      AuthenticatedConsoleX7q9f4k2m8InventoryRoute,
    AuthenticatedConsoleX7q9f4k2m8KycRoute:
      AuthenticatedConsoleX7q9f4k2m8KycRoute,
    AuthenticatedConsoleX7q9f4k2m8MembersRoute:
      AuthenticatedConsoleX7q9f4k2m8MembersRoute,
    AuthenticatedConsoleX7q9f4k2m8OrdersRoute:
      AuthenticatedConsoleX7q9f4k2m8OrdersRoute,
    AuthenticatedConsoleX7q9f4k2m8ProductsRoute:
      AuthenticatedConsoleX7q9f4k2m8ProductsRoute,
    AuthenticatedConsoleX7q9f4k2m8RanksRoute:
      AuthenticatedConsoleX7q9f4k2m8RanksRoute,
    AuthenticatedConsoleX7q9f4k2m8StaffRoute:
      AuthenticatedConsoleX7q9f4k2m8StaffRoute,
    AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute:
      AuthenticatedConsoleX7q9f4k2m8WithdrawalsRoute,
    AuthenticatedConsoleX7q9f4k2m8IndexRoute:
      AuthenticatedConsoleX7q9f4k2m8IndexRoute,
  }

const AuthenticatedConsoleX7q9f4k2m8RouteWithChildren =
  AuthenticatedConsoleX7q9f4k2m8Route._addFileChildren(
    AuthenticatedConsoleX7q9f4k2m8RouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardKycRoute: typeof AuthenticatedDashboardKycRoute
  AuthenticatedDashboardMatrixRoute: typeof AuthenticatedDashboardMatrixRoute
  AuthenticatedDashboardMembershipRoute: typeof AuthenticatedDashboardMembershipRoute
  AuthenticatedDashboardNewsRoute: typeof AuthenticatedDashboardNewsRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPerformanceRoute: typeof AuthenticatedDashboardPerformanceRoute
  AuthenticatedDashboardWalletRoute: typeof AuthenticatedDashboardWalletRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardKycRoute: AuthenticatedDashboardKycRoute,
    AuthenticatedDashboardMatrixRoute: AuthenticatedDashboardMatrixRoute,
    AuthenticatedDashboardMembershipRoute:
      AuthenticatedDashboardMembershipRoute,
    AuthenticatedDashboardNewsRoute: AuthenticatedDashboardNewsRoute,
    AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
    AuthenticatedDashboardPerformanceRoute:
      AuthenticatedDashboardPerformanceRoute,
    AuthenticatedDashboardWalletRoute: AuthenticatedDashboardWalletRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConsoleX7q9f4k2m8Route: typeof AuthenticatedConsoleX7q9f4k2m8RouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConsoleX7q9f4k2m8Route:
    AuthenticatedConsoleX7q9f4k2m8RouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  RegisterRoute: RegisterRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicHooksLicenseGraceRoute: ApiPublicHooksLicenseGraceRoute,
  ApiPublicHooksMatrixCommissionsRoute: ApiPublicHooksMatrixCommissionsRoute,
  ApiPublicHooksMonthlyCycleRoute: ApiPublicHooksMonthlyCycleRoute,
  ApiPublicHooksWeeklyCycleRoute: ApiPublicHooksWeeklyCycleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
