REVOKE EXECUTE ON FUNCTION public.request_withdrawal(integer, public.payment_method, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_review_withdrawal(uuid, boolean, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_review_kyc(uuid, boolean, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_adjust_wallet(uuid, integer, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_wallet_frozen(uuid, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_member_status(uuid, public.member_status) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_assign_role(uuid, public.app_role, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_role_permission(public.app_role, text, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_permission(uuid, text, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_upsert_product(uuid, text, text, text, text, integer, integer, integer, text[], integer, public.product_status) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_stock(uuid, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_order_status(uuid, public.order_status) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_set_commission_status(uuid, public.commission_status, integer, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_update_rank(text, integer, integer, integer, integer, numeric) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_upsert_announcement(uuid, text, text, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_upsert_gallery_feature(uuid, text, text, text, text, boolean) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_report_stats() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_staff(uuid) FROM anon, public;

GRANT EXECUTE ON FUNCTION public.request_withdrawal(integer, public.payment_method, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_review_withdrawal(uuid, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_review_kyc(uuid, boolean, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_adjust_wallet(uuid, integer, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_wallet_frozen(uuid, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_member_status(uuid, public.member_status) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_assign_role(uuid, public.app_role, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_role_permission(public.app_role, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_permission(uuid, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_product(uuid, text, text, text, text, integer, integer, integer, text[], integer, public.product_status) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_stock(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_order_status(uuid, public.order_status) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_commission_status(uuid, public.commission_status, integer, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_rank(text, integer, integer, integer, integer, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_announcement(uuid, text, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_upsert_gallery_feature(uuid, text, text, text, text, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_report_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_permission(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;